### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by sandeep131** [nightborn-be/signum#2]
HI - This looks great and thank you for making it available.. I was trying to install and run this project to get inspiration on some of the work.  I am having issue with the rollup failing.  Have you come across this or may be I am missing some config step?

I saw some issues related to async support on rollup but that does not seem like it...

Generally new to the React env so it may be something simple.... Would appreciate your help.  Thx.

> @nightborn/signum@1.0.5 start /Users/sandeep/Downloads/signum-master
> rollup -c -w

/Users/sandeep/Downloads/signum-master/node_modules/rollup/dist/shared/loadConfigFile.js:484
        ? (await import(url.pathToFileURL(fileName).href)).default
                 ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sandeep/Downloads/signum-master/node_modules/rollup/dist/bin/rollup:23:25)

**Comment by m-Nightly** [comment]
Hey there, that's strange I did not have this problem. 

What version of rollup was installed in the node_modules?

**Comment by sandeep131** [comment]
Thanks, Looks like the latest version 2.6.1 - which version do you have?  

devDependencies shows:
    "@rollup/plugin-image": "^2.0.4",
    "@rollup/plugin-typescript": "^4.0.0",
    "@wessberg/rollup-plugin-ts": "^1.2.24",
    "rollup": "^2.4.0",
    "rollup-plugin-babel": "^4.4.0",
    "rollup-plugin-scss": "^2.1.0"

**Comment by m-Nightly** [comment]
2.4.0 indeed, but you used npm I suppose? I published my yarn.lock on the git, but I could fix the versions of all the dependencies in the package.json, I'll do that tonight. :)
