### ISSUE TITLE
Key prop is missing

### ISSUE THREAD

**Issue by naorye** [nightborn-be/signum#3]
When using Chat with multiple options, I get:

![image](https://user-images.githubusercontent.com/2873571/79700524-e95f4500-829e-11ea-812c-7f556f5d5bf6.png)

**Comment by naorye** [comment]
Added a pull request to fix this and other issues
https://github.com/nightborn-be/signum/pull/4

**Comment by m-Nightly** [comment]
@naorye I looked at your pull request, those are good changes, a different coding style for the types, we prefer them in subfolders where they're used. A little like the "common denominator" but the other changes were indeed needed for an opensource project. Thanks :)

**Comment by naorye** [comment]
@m-Nightly Thanks!
2 reasons why I changed the types structure:
1. It was difficult for me to find the types
2. In order to expose the types I needed a single entry point with all the types
This led to that change.

Anyway, I glad you merged this pr :)
